apiVersion: v1
kind: Service
metadata:
  name: {{ include "gestuser.fullname" . }}
  labels:
    {{- include "gestuser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gestuser.selectorLabels" . | nindent 4 }}
